
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:${DOCKER_PATH}/api"
      - "${DOCKER_PATH}/api/node_modules"
    env_file:
      - .env
    expose:
      - '3001:3001'
    depends_on:
        - db
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - "./web:${DOCKER_PATH}/web"
      - "${DOCKER_PATH}/web/node_modules"
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
        - app

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    expose:
      - '5432'
    restart: always

  nginx:
    depends_on:
      - app
      - db
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/var/www/static
    restart: always


