
services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "./api:${DOCKER_PATH}/api"
      - "${DOCKER_PATH}/api/node_modules"
      - ./uploads:/api/uploads
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3001"
    restart: unless-stopped
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always