
services:
  app:
    image: git.rdcenter.ru/rdcenter/stolentogermany/stolentogermany-backend:main
    volumes:
      - "${DOCKER_PATH}/api/node_modules"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
    ports:
      - '3001:3001'  # Изменено с expose на ports для доступа извне
    depends_on:
      - db
    restart: unless-stopped

  web:
    image: git.rdcenter.ru/rdcenter/stolentogermany/stolentogermany-frontend:main
    env_file:
      - .env
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - app

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'  # Изменено с expose на ports для доступа извне
    restart: always